services:
  app:
    container_name: mediawiki_app
    depends_on:
      - db
    build: ./
    restart: always
    ports:
      - 80:80
    # volumes:
    #   - ./images:/var/www/mediawiki/images/
    env_file:
      - .env
  db:
    container_name: mediawiki_db
    image: mariadb
    restart: always
    # volumes:
    #   - ./db_data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
version: "3.2"